/*
 * syscall.h
 *
 *  Created on: Jul 13, 2016
 *      Author: jrobbins
 */

#ifndef LIBC_SYS_SYSCALL_H_
#define LIBC_SYS_SYSCALL_H_

// This header is a GNU extension. Do not use for strictly POSIX-compliant work.

/*
TODO: Some of this might be public, kernel-independent interface, and some might be kernel-dependent.
The kernel-dependent bits need to be enumerated, sorted out, and made machdep-specific.
*/

#define __NR_pselect6               0
#define __NR_ulimit                 1
#define __NR_adjtimex               2
#define __NR_sigprocmask            3
#define __NR_iopl                   4
#define __NR_pipe2                  5
#define __NR_wait4                  6
#define __NR_umask                  7
#define __NR_ftruncate64            8
#define __NR_sendmmsg               9
#define __NR_link                   10
#define __NR_dup3                   11
#define __NR_setfsgid32             12
#define __NR_vmsplice               13
#define __NR_timer_settime          14
#define __NR_mmap2                  15
#define __NR_msgsnd                 16
#define __NR_prctl                  17
#define __NR_ugetrlimit             18
#define __NR_chmod                  19
#define __NR_sched_getaffinity      20
#define __NR_recvmsg                21
#define __NR_setgroups32            22
#define __NR_modify_ldt             23
#define __NR_vhangup                24
#define __NR_keyctl                 25
#define __NR_rt_sigsuspend          26
#define __NR_splice                 27
#define __NR_faccessat              28
#define __NR_finit_module           29
#define __NR_fadvise64_64           30
#define __NR_name_to_handle_at      31
#define __NR_fcntl                  32
#define __NR_get_kernel_syms        33
#define __NR_capset                 34
#define __NR_pause                  35
#define __NR_getgroups32            36
#define __NR_sched_get_priority_max 37
#define __NR_fstatfs                38
#define __NR_flistxattr             39
#define __NR_setpriority            40
#define __NR_sync_file_range        41
#define __NR_setsockopt             42
#define __NR_msync                  43
#define __NR_setresgid              44
#define __NR_epoll_create           45
#define __NR_move_pages             46
#define __NR_mremap                 47
#define __NR_brk                    48
#define __NR_fchmod                 49
#define __NR_fcntl64                50
#define __NR_readlinkat             51
#define __NR_setresuid32            52
#define __NR_mprotect               53
#define __NR_break                  54
#define __NR_dup2                   55
#define __NR_mmap                   56
#define __NR_process_vm_writev      57
#define __NR_fstatat64              58
#define __NR_nfsservctl             59
#define __NR_close                  60
#define __NR_unshare                61
#define __NR_waitpid                62
#define __NR_pwritev                63
#define __NR_getpgrp                64
#define __NR_setfsgid               65
#define __NR_ipc                    66
#define __NR_mlockall               67
#define __NR_llistxattr             68
#define __NR_io_destroy             69
#define __NR_clone                  70
#define __NR_getresgid              71
#define __NR_getrusage              72
#define __NR_rt_sigqueueinfo        73
#define __NR_quotactl               74
#define __NR_unlink                 75
#define __NR_perf_event_open        76
#define __NR_timer_create           77
#define __NR_delete_module          78
#define __NR_getgid32               79
#define __NR_connect                80
#define __NR_mkdirat                81
#define __NR__llseek                82
#define __NR_getsid                 83
#define __NR_epoll_create1          84
#define __NR_rename                 85
#define __NR_setgid32               86
#define __NR_seccomp                87
#define __NR_pipe                   88
#define __NR_writev                 89
#define __NR_vm86old                90
#define __NR_bpf                    91
#define __NR_ioprio_get             92
#define __NR_timer_getoverrun       93
#define __NR_oldlstat               94
#define __NR_clock_settime          95
#define __NR_fremovexattr           96
#define __NR_io_submit              97
#define __NR_fchdir                 98
#define __NR_mincore                99
#define __NR_getsockname            100
#define __NR_setns                  101
#define __NR_getpmsg                102
#define __NR_ptrace                 103
#define __NR_symlink                104
#define __NR_getxattr               105
#define __NR_timerfd_gettime        106
#define __NR_getresuid              107
#define __NR_setreuid32             108
#define __NR_ioprio_set             109
#define __NR_mlock                  110
#define __NR_syslog                 111
#define __NR_lstat64                112
#define __NR_accept                 113
#define __NR_getpgid                114
#define __NR_tuxcall                115
#define __NR_ioperm                 116
#define __NR_query_module           117
#define __NR_acct                   118
#define __NR_mq_unlink              119
#define __NR_create_module          120
#define __NR_uselib                 121
#define __NR_utimes                 122
#define __NR_dup                    123
#define __NR_lock                   124
#define __NR_clock_getres           125
#define __NR_kexec_load             126
#define __NR_getcpu                 127
#define __NR_fchown32               128
#define __NR_add_key                129
#define __NR_shmget                 130
#define __NR_mbind                  131
#define __NR_shmdt                  132
#define __NR_rt_sigreturn           133
#define __NR_shmctl                 134
#define __NR_semget                 135
#define __NR_timer_delete           136
#define __NR_semtimedop             137
#define __NR_semop                  138
#define __NR_shmat                  139
#define __NR_semctl                 140
#define __NR_security               141
#define __NR_newfstatat             142
#define __NR_sysinfo                143
#define __NR_recvfrom               144
#define __NR_msgrcv                 145
#define __NR_msgget                 146
#define __NR_tkill                  147
#define __NR_msgctl                 148
#define __NR_mq_timedreceive        149
#define __NR_kexec_file_load        150
#define __NR_epoll_wait_old         151
#define __NR_epoll_ctl_old          152
#define __NR_arch_prctl             153
#define __NR_write                  154
#define __NR_ftime                  155
#define __NR_waitid                 156
#define __NR_vserver                157
#define __NR_mq_getsetattr          158
#define __NR_vm86                   159
#define __NR_timerfd_settime        160
#define __NR_setdomainname          161
#define __NR_memfd_create           162
#define __NR_utimensat              163
#define __NR_utime                  164
#define __NR_ustat                  165
#define __NR_userfaultfd            166
#define __NR_unlinkat               167
#define __NR_uname                  168
#define __NR_umount2                169
#define __NR_io_setup               170
#define __NR__newselect             171
#define __NR_sigaltstack            172
#define __NR_truncate64             173
#define __NR_truncate               174
#define __NR_times                  175
#define __NR_olduname               176
#define __NR_lgetxattr              177
#define __NR_vfork                  178
#define __NR_setresgid32            179
#define __NR_timerfd_create         180
#define __NR_eventfd2               181
#define __NR_rt_sigaction           182
#define __NR_openat                 183
#define __NR_fchownat               184
#define __NR_sendfile               185
#define __NR_fstatfs64              186
#define __NR_accept4                187
#define __NR_chown                  188
#define __NR_time                   189
#define __NR_tgkill                 190
#define __NR_tee                    191
#define __NR_sched_setparam         192
#define __NR_sysfs                  193
#define __NR_getgroups              194
#define __NR_remap_file_pages       195
#define __NR_readahead              196
#define __NR_mq_open                197
#define __NR_pwrite64               198
#define __NR_syncfs                 199
#define __NR_stty                   200
#define __NR_symlinkat              201
#define __NR_swapon                 202
#define __NR_getdents               203
#define __NR_swapoff                204
#define __NR_sync                   205
#define __NR_setresuid              206
#define __NR_stime                  207
#define __NR_lsetxattr              208
#define __NR_kcmp                   209
#define __NR_restart_syscall        210
#define __NR_oldfstat               211
#define __NR_fadvise64              212
#define __NR_statfs64               213
#define __NR_statfs                 214
#define __NR_kill                   215
#define __NR_stat64                 216
#define __NR_set_mempolicy          217
#define __NR_ssetmask               218
#define __NR_mkdir                  219
#define __NR_lremovexattr           220
#define __NR_gettid                 221
#define __NR_socketpair             222
#define __NR_pread64                223
#define __NR_lookup_dcookie         224
#define __NR_mq_notify              225
#define __NR_get_mempolicy          226
#define __NR_socketcall             227
#define __NR_listxattr              228
#define __NR_fchmodat               229
#define __NR_sigsuspend             230
#define __NR_get_thread_area        231
#define __NR_reboot                 232
#define __NR_signalfd4              233
#define __NR_lseek                  234
#define __NR_signalfd               235
#define __NR_signal                 236
#define __NR_fdatasync              237
#define __NR_chown32                238
#define __NR_munlock                239
#define __NR_umount                 240
#define __NR_sigaction              241
#define __NR_shutdown               242
#define __NR_setuid                 243
#define __NR_geteuid                244
#define __NR_sgetmask               245
#define __NR_sched_setscheduler     246
#define __NR_setxattr               247
#define __NR_epoll_wait             248
#define __NR_fork                   249
#define __NR_setuid32               250
#define __NR_settimeofday           251
#define __NR_sendmsg                252
#define __NR_set_tid_address        253
#define __NR_io_getevents           254
#define __NR_madvise                255
#define __NR_setrlimit              256
#define __NR_gtty                   257
#define __NR_setreuid               258
#define __NR_setregid32             259
#define __NR_setregid               260
#define __NR_sched_setaffinity      261
#define __NR_setpgid                262
#define __NR_setitimer              263
#define __NR_flock                  264
#define __NR_sethostname            265
#define __NR_chdir                  266
#define __NR_geteuid32              267
#define __NR_fstat                  268
#define __NR__sysctl                269
#define __NR_fgetxattr              270
#define __NR_epoll_ctl              271
#define __NR_setgroups              272
#define __NR_bind                   273
#define __NR_setgid                 274
#define __NR_setfsuid32             275
#define __NR_setfsuid               276
#define __NR_mlock2                 277
#define __NR_inotify_rm_watch       278
#define __NR_set_robust_list        279
#define __NR_fchown                 280
#define __NR_stat                   281
#define __NR_sendto                 282
#define __NR_setsid                 283
#define __NR_lchown                 284
#define __NR_ppoll                  285
#define __NR_select                 286
#define __NR_sched_yield            287
#define __NR_sched_setattr          288
#define __NR_fstat64                289
#define __NR_profil                 290
#define __NR_sched_getscheduler     291
#define __NR_sched_getparam         292
#define __NR_linkat                 293
#define __NR_munlockall             294
#define __NR_sched_get_priority_min 295
#define __NR_sched_rr_get_interval  296
#define __NR_rt_tgsigqueueinfo      297
#define __NR_eventfd                298
#define __NR_preadv                 299
#define __NR_getsockopt             300
#define __NR_rt_sigprocmask         301
#define __NR_rt_sigpending          302
#define __NR_readv                  303
#define __NR_rmdir                  304
#define __NR_fanotify_init          305
#define __NR_getppid                306
#define __NR_capget                 307
#define __NR_renameat2              308
#define __NR_getpriority            309
#define __NR_readlink               310
#define __NR_recvmmsg               311
#define __NR_exit_group             312
#define __NR_getegid32              313
#define __NR_read                   314
#define __NR_open                   315
#define __NR_getuid32               316
#define __NR_futex                  317
#define __NR_sigpending             318
#define __NR_membarrier             319
#define __NR_readdir                320
#define __NR_fsetxattr              321
#define __NR_mknod                  322
#define __NR_removexattr            323
#define __NR_getresgid32            324
#define __NR_get_robust_list        325
#define __NR_afs_syscall            326
#define __NR_clock_gettime          327
#define __NR_getuid                 328
#define __NR_prlimit64              329
#define __NR_mq_timedsend           330
#define __NR_nice                   331
#define __NR_clock_adjtime          332
#define __NR_listen                 333
#define __NR_ioctl                  334
#define __NR_getpeername            335
#define __NR_mknodat                336
#define __NR_bdflush                337
#define __NR_migrate_pages          338
#define __NR_clock_nanosleep        339
#define __NR_futimesat              340
#define __NR_process_vm_readv       341
#define __NR_sendfile64             342
#define __NR_lchown32               343
#define __NR_poll                   344
#define __NR_inotify_init           345
#define __NR_getegid                346
#define __NR_pivot_root             347
#define __NR_personality            348
#define __NR_open_by_handle_at      349
#define __NR_getitimer              350
#define __NR_epoll_pwait            351
#define __NR_getrlimit              352
#define __NR_getcwd                 353
#define __NR_gettimeofday           354
#define __NR_renameat               355
#define __NR_mpx                    356
#define __NR_oldolduname            357
#define __NR_execve                 358
#define __NR_sigreturn              359
#define __NR_chroot                 360
#define __NR_idle                   361
#define __NR_execveat               362
#define __NR_ftruncate              363
#define __NR_request_key            364
#define __NR_getresuid32            365
#define __NR_getrandom              366
#define __NR_getpid                 367
#define __NR_fsync                  368
#define __NR_munmap                 369
#define __NR_mount                  370
#define __NR_getgid                 371
#define __NR_access                 372
#define __NR_oldstat                373
#define __NR_inotify_init1          374
#define __NR_fallocate              375
#define __NR_rt_sigtimedwait        376
#define __NR_alarm                  377
#define __NR_nanosleep              378
#define __NR_sched_getattr          379
#define __NR_getdents64             380
#define __NR_inotify_add_watch      381
#define __NR_socket                 382
#define __NR_putpmsg                383
#define __NR_io_cancel              384
#define __NR_fanotify_mark          385
#define __NR_exit                   386
#define __NR_set_thread_area        387
#define __NR_lstat                  388
#define __NR_init_module            389
#define __NR_prof                   390
#define __NR_timer_gettime          391
#define __NR_creat                  392

#define SYS_pselect6               __NR_pselect6
#define SYS_ulimit                 __NR_ulimit
#define SYS_adjtimex               __NR_adjtimex
#define SYS_sigprocmask            __NR_sigprocmask
#define SYS_iopl                   __NR_iopl
#define SYS_pipe2                  __NR_pipe2
#define SYS_wait4                  __NR_wait4
#define SYS_umask                  __NR_umask
#define SYS_ftruncate64            __NR_ftruncate64
#define SYS_sendmmsg               __NR_sendmmsg
#define SYS_link                   __NR_link
#define SYS_dup3                   __NR_dup3
#define SYS_setfsgid32             __NR_setfsgid32
#define SYS_vmsplice               __NR_vmsplice
#define SYS_timer_settime          __NR_timer_settime
#define SYS_mmap2                  __NR_mmap2
#define SYS_msgsnd                 __NR_msgsnd
#define SYS_prctl                  __NR_prctl
#define SYS_ugetrlimit             __NR_ugetrlimit
#define SYS_chmod                  __NR_chmod
#define SYS_sched_getaffinity      __NR_sched_getaffinity
#define SYS_recvmsg                __NR_recvmsg
#define SYS_setgroups32            __NR_setgroups32
#define SYS_modify_ldt             __NR_modify_ldt
#define SYS_vhangup                __NR_vhangup
#define SYS_keyctl                 __NR_keyctl
#define SYS_rt_sigsuspend          __NR_rt_sigsuspend
#define SYS_splice                 __NR_splice
#define SYS_faccessat              __NR_faccessat
#define SYS_finit_module           __NR_finit_module
#define SYS_fadvise64_64           __NR_fadvise64_64
#define SYS_name_to_handle_at      __NR_name_to_handle_at
#define SYS_fcntl                  __NR_fcntl
#define SYS_get_kernel_syms        __NR_get_kernel_syms
#define SYS_capset                 __NR_capset
#define SYS_pause                  __NR_pause
#define SYS_getgroups32            __NR_getgroups32
#define SYS_sched_get_priority_max __NR_sched_get_priority_max
#define SYS_fstatfs                __NR_fstatfs
#define SYS_flistxattr             __NR_flistxattr
#define SYS_setpriority            __NR_setpriority
#define SYS_sync_file_range        __NR_sync_file_range
#define SYS_setsockopt             __NR_setsockopt
#define SYS_msync                  __NR_msync
#define SYS_setresgid              __NR_setresgid
#define SYS_epoll_create           __NR_epoll_create
#define SYS_move_pages             __NR_move_pages
#define SYS_mremap                 __NR_mremap
#define SYS_brk                    __NR_brk
#define SYS_fchmod                 __NR_fchmod
#define SYS_fcntl64                __NR_fcntl64
#define SYS_readlinkat             __NR_readlinkat
#define SYS_setresuid32            __NR_setresuid32
#define SYS_mprotect               __NR_mprotect
#define SYS_break                  __NR_break
#define SYS_dup2                   __NR_dup2
#define SYS_mmap                   __NR_mmap
#define SYS_process_vm_writev      __NR_process_vm_writev
#define SYS_fstatat64              __NR_fstatat64
#define SYS_nfsservctl             __NR_nfsservctl
#define SYS_close                  __NR_close
#define SYS_unshare                __NR_unshare
#define SYS_waitpid                __NR_waitpid
#define SYS_pwritev                __NR_pwritev
#define SYS_getpgrp                __NR_getpgrp
#define SYS_setfsgid               __NR_setfsgid
#define SYS_ipc                    __NR_ipc
#define SYS_mlockall               __NR_mlockall
#define SYS_llistxattr             __NR_llistxattr
#define SYS_io_destroy             __NR_io_destroy
#define SYS_clone                  __NR_clone
#define SYS_getresgid              __NR_getresgid
#define SYS_getrusage              __NR_getrusage
#define SYS_rt_sigqueueinfo        __NR_rt_sigqueueinfo
#define SYS_quotactl               __NR_quotactl
#define SYS_unlink                 __NR_unlink
#define SYS_perf_event_open        __NR_perf_event_open
#define SYS_timer_create           __NR_timer_create
#define SYS_delete_module          __NR_delete_module
#define SYS_getgid32               __NR_getgid32
#define SYS_connect                __NR_connect
#define SYS_mkdirat                __NR_mkdirat
#define SYS__llseek                __NR__llseek
#define SYS_getsid                 __NR_getsid
#define SYS_epoll_create1          __NR_epoll_create1
#define SYS_rename                 __NR_rename
#define SYS_setgid32               __NR_setgid32
#define SYS_seccomp                __NR_seccomp
#define SYS_pipe                   __NR_pipe
#define SYS_writev                 __NR_writev
#define SYS_vm86old                __NR_vm86old
#define SYS_bpf                    __NR_bpf
#define SYS_ioprio_get             __NR_ioprio_get
#define SYS_timer_getoverrun       __NR_timer_getoverrun
#define SYS_oldlstat               __NR_oldlstat
#define SYS_clock_settime          __NR_clock_settime
#define SYS_fremovexattr           __NR_fremovexattr
#define SYS_io_submit              __NR_io_submit
#define SYS_fchdir                 __NR_fchdir
#define SYS_mincore                __NR_mincore
#define SYS_getsockname            __NR_getsockname
#define SYS_setns                  __NR_setns
#define SYS_getpmsg                __NR_getpmsg
#define SYS_ptrace                 __NR_ptrace
#define SYS_symlink                __NR_symlink
#define SYS_getxattr               __NR_getxattr
#define SYS_timerfd_gettime        __NR_timerfd_gettime
#define SYS_getresuid              __NR_getresuid
#define SYS_setreuid32             __NR_setreuid32
#define SYS_ioprio_set             __NR_ioprio_set
#define SYS_mlock                  __NR_mlock
#define SYS_syslog                 __NR_syslog
#define SYS_lstat64                __NR_lstat64
#define SYS_accept                 __NR_accept
#define SYS_getpgid                __NR_getpgid
#define SYS_tuxcall                __NR_tuxcall
#define SYS_ioperm                 __NR_ioperm
#define SYS_query_module           __NR_query_module
#define SYS_acct                   __NR_acct
#define SYS_mq_unlink              __NR_mq_unlink
#define SYS_create_module          __NR_create_module
#define SYS_uselib                 __NR_uselib
#define SYS_utimes                 __NR_utimes
#define SYS_dup                    __NR_dup
#define SYS_lock                   __NR_lock
#define SYS_clock_getres           __NR_clock_getres
#define SYS_kexec_load             __NR_kexec_load
#define SYS_getcpu                 __NR_getcpu
#define SYS_fchown32               __NR_fchown32
#define SYS_add_key                __NR_add_key
#define SYS_shmget                 __NR_shmget
#define SYS_mbind                  __NR_mbind
#define SYS_shmdt                  __NR_shmdt
#define SYS_rt_sigreturn           __NR_rt_sigreturn
#define SYS_shmctl                 __NR_shmctl
#define SYS_semget                 __NR_semget
#define SYS_timer_delete           __NR_timer_delete
#define SYS_semtimedop             __NR_semtimedop
#define SYS_semop                  __NR_semop
#define SYS_shmat                  __NR_shmat
#define SYS_semctl                 __NR_semctl
#define SYS_security               __NR_security
#define SYS_newfstatat             __NR_newfstatat
#define SYS_sysinfo                __NR_sysinfo
#define SYS_recvfrom               __NR_recvfrom
#define SYS_msgrcv                 __NR_msgrcv
#define SYS_msgget                 __NR_msgget
#define SYS_tkill                  __NR_tkill
#define SYS_msgctl                 __NR_msgctl
#define SYS_mq_timedreceive        __NR_mq_timedreceive
#define SYS_kexec_file_load        __NR_kexec_file_load
#define SYS_epoll_wait_old         __NR_epoll_wait_old
#define SYS_epoll_ctl_old          __NR_epoll_ctl_old
#define SYS_arch_prctl             __NR_arch_prctl
#define SYS_write                  __NR_write
#define SYS_ftime                  __NR_ftime
#define SYS_waitid                 __NR_waitid
#define SYS_vserver                __NR_vserver
#define SYS_mq_getsetattr          __NR_mq_getsetattr
#define SYS_vm86                   __NR_vm86
#define SYS_timerfd_settime        __NR_timerfd_settime
#define SYS_setdomainname          __NR_setdomainname
#define SYS_memfd_create           __NR_memfd_create
#define SYS_utimensat              __NR_utimensat
#define SYS_utime                  __NR_utime
#define SYS_ustat                  __NR_ustat
#define SYS_userfaultfd            __NR_userfaultfd
#define SYS_unlinkat               __NR_unlinkat
#define SYS_uname                  __NR_uname
#define SYS_umount2                __NR_umount2
#define SYS_io_setup               __NR_io_setup
#define SYS__newselect             __NR__newselect
#define SYS_sigaltstack            __NR_sigaltstack
#define SYS_truncate64             __NR_truncate64
#define SYS_truncate               __NR_truncate
#define SYS_times                  __NR_times
#define SYS_olduname               __NR_olduname
#define SYS_lgetxattr              __NR_lgetxattr
#define SYS_vfork                  __NR_vfork
#define SYS_setresgid32            __NR_setresgid32
#define SYS_timerfd_create         __NR_timerfd_create
#define SYS_eventfd2               __NR_eventfd2
#define SYS_rt_sigaction           __NR_rt_sigaction
#define SYS_openat                 __NR_openat
#define SYS_fchownat               __NR_fchownat
#define SYS_sendfile               __NR_sendfile
#define SYS_fstatfs64              __NR_fstatfs64
#define SYS_accept4                __NR_accept4
#define SYS_chown                  __NR_chown
#define SYS_time                   __NR_time
#define SYS_tgkill                 __NR_tgkill
#define SYS_tee                    __NR_tee
#define SYS_sched_setparam         __NR_sched_setparam
#define SYS_sysfs                  __NR_sysfs
#define SYS_getgroups              __NR_getgroups
#define SYS_remap_file_pages       __NR_remap_file_pages
#define SYS_readahead              __NR_readahead
#define SYS_mq_open                __NR_mq_open
#define SYS_pwrite64               __NR_pwrite64
#define SYS_syncfs                 __NR_syncfs
#define SYS_stty                   __NR_stty
#define SYS_symlinkat              __NR_symlinkat
#define SYS_swapon                 __NR_swapon
#define SYS_getdents               __NR_getdents
#define SYS_swapoff                __NR_swapoff
#define SYS_sync                   __NR_sync
#define SYS_setresuid              __NR_setresuid
#define SYS_stime                  __NR_stime
#define SYS_lsetxattr              __NR_lsetxattr
#define SYS_kcmp                   __NR_kcmp
#define SYS_restart_syscall        __NR_restart_syscall
#define SYS_oldfstat               __NR_oldfstat
#define SYS_fadvise64              __NR_fadvise64
#define SYS_statfs64               __NR_statfs64
#define SYS_statfs                 __NR_statfs
#define SYS_kill                   __NR_kill
#define SYS_stat64                 __NR_stat64
#define SYS_set_mempolicy          __NR_set_mempolicy
#define SYS_ssetmask               __NR_ssetmask
#define SYS_mkdir                  __NR_mkdir
#define SYS_lremovexattr           __NR_lremovexattr
#define SYS_gettid                 __NR_gettid
#define SYS_socketpair             __NR_socketpair
#define SYS_pread64                __NR_pread64
#define SYS_lookup_dcookie         __NR_lookup_dcookie
#define SYS_mq_notify              __NR_mq_notify
#define SYS_get_mempolicy          __NR_get_mempolicy
#define SYS_socketcall             __NR_socketcall
#define SYS_listxattr              __NR_listxattr
#define SYS_fchmodat               __NR_fchmodat
#define SYS_sigsuspend             __NR_sigsuspend
#define SYS_get_thread_area        __NR_get_thread_area
#define SYS_reboot                 __NR_reboot
#define SYS_signalfd4              __NR_signalfd4
#define SYS_lseek                  __NR_lseek
#define SYS_signalfd               __NR_signalfd
#define SYS_signal                 __NR_signal
#define SYS_fdatasync              __NR_fdatasync
#define SYS_chown32                __NR_chown32
#define SYS_munlock                __NR_munlock
#define SYS_umount                 __NR_umount
#define SYS_sigaction              __NR_sigaction
#define SYS_shutdown               __NR_shutdown
#define SYS_setuid                 __NR_setuid
#define SYS_geteuid                __NR_geteuid
#define SYS_sgetmask               __NR_sgetmask
#define SYS_sched_setscheduler     __NR_sched_setscheduler
#define SYS_setxattr               __NR_setxattr
#define SYS_epoll_wait             __NR_epoll_wait
#define SYS_fork                   __NR_fork
#define SYS_setuid32               __NR_setuid32
#define SYS_settimeofday           __NR_settimeofday
#define SYS_sendmsg                __NR_sendmsg
#define SYS_set_tid_address        __NR_set_tid_address
#define SYS_io_getevents           __NR_io_getevents
#define SYS_madvise                __NR_madvise
#define SYS_setrlimit              __NR_setrlimit
#define SYS_gtty                   __NR_gtty
#define SYS_setreuid               __NR_setreuid
#define SYS_setregid32             __NR_setregid32
#define SYS_setregid               __NR_setregid
#define SYS_sched_setaffinity      __NR_sched_setaffinity
#define SYS_setpgid                __NR_setpgid
#define SYS_setitimer              __NR_setitimer
#define SYS_flock                  __NR_flock
#define SYS_sethostname            __NR_sethostname
#define SYS_chdir                  __NR_chdir
#define SYS_geteuid32              __NR_geteuid32
#define SYS_fstat                  __NR_fstat
#define SYS__sysctl                __NR__sysctl
#define SYS_fgetxattr              __NR_fgetxattr
#define SYS_epoll_ctl              __NR_epoll_ctl
#define SYS_setgroups              __NR_setgroups
#define SYS_bind                   __NR_bind
#define SYS_setgid                 __NR_setgid
#define SYS_setfsuid32             __NR_setfsuid32
#define SYS_setfsuid               __NR_setfsuid
#define SYS_mlock2                 __NR_mlock2
#define SYS_inotify_rm_watch       __NR_inotify_rm_watch
#define SYS_set_robust_list        __NR_set_robust_list
#define SYS_fchown                 __NR_fchown
#define SYS_stat                   __NR_stat
#define SYS_sendto                 __NR_sendto
#define SYS_setsid                 __NR_setsid
#define SYS_lchown                 __NR_lchown
#define SYS_ppoll                  __NR_ppoll
#define SYS_select                 __NR_select
#define SYS_sched_yield            __NR_sched_yield
#define SYS_sched_setattr          __NR_sched_setattr
#define SYS_fstat64                __NR_fstat64
#define SYS_profil                 __NR_profil
#define SYS_sched_getscheduler     __NR_sched_getscheduler
#define SYS_sched_getparam         __NR_sched_getparam
#define SYS_linkat                 __NR_linkat
#define SYS_munlockall             __NR_munlockall
#define SYS_sched_get_priority_min __NR_sched_get_priority_min
#define SYS_sched_rr_get_interval  __NR_sched_rr_get_interval
#define SYS_rt_tgsigqueueinfo      __NR_rt_tgsigqueueinfo
#define SYS_eventfd                __NR_eventfd
#define SYS_preadv                 __NR_preadv
#define SYS_getsockopt             __NR_getsockopt
#define SYS_rt_sigprocmask         __NR_rt_sigprocmask
#define SYS_rt_sigpending          __NR_rt_sigpending
#define SYS_readv                  __NR_readv
#define SYS_rmdir                  __NR_rmdir
#define SYS_fanotify_init          __NR_fanotify_init
#define SYS_getppid                __NR_getppid
#define SYS_capget                 __NR_capget
#define SYS_renameat2              __NR_renameat2
#define SYS_getpriority            __NR_getpriority
#define SYS_readlink               __NR_readlink
#define SYS_recvmmsg               __NR_recvmmsg
#define SYS_exit_group             __NR_exit_group
#define SYS_getegid32              __NR_getegid32
#define SYS_read                   __NR_read
#define SYS_open                   __NR_open
#define SYS_getuid32               __NR_getuid32
#define SYS_futex                  __NR_futex
#define SYS_sigpending             __NR_sigpending
#define SYS_membarrier             __NR_membarrier
#define SYS_readdir                __NR_readdir
#define SYS_fsetxattr              __NR_fsetxattr
#define SYS_mknod                  __NR_mknod
#define SYS_removexattr            __NR_removexattr
#define SYS_getresgid32            __NR_getresgid32
#define SYS_get_robust_list        __NR_get_robust_list
#define SYS_afs_syscall            __NR_afs_syscall
#define SYS_clock_gettime          __NR_clock_gettime
#define SYS_getuid                 __NR_getuid
#define SYS_prlimit64              __NR_prlimit64
#define SYS_mq_timedsend           __NR_mq_timedsend
#define SYS_nice                   __NR_nice
#define SYS_clock_adjtime          __NR_clock_adjtime
#define SYS_listen                 __NR_listen
#define SYS_ioctl                  __NR_ioctl
#define SYS_getpeername            __NR_getpeername
#define SYS_mknodat                __NR_mknodat
#define SYS_bdflush                __NR_bdflush
#define SYS_migrate_pages          __NR_migrate_pages
#define SYS_clock_nanosleep        __NR_clock_nanosleep
#define SYS_futimesat              __NR_futimesat
#define SYS_process_vm_readv       __NR_process_vm_readv
#define SYS_sendfile64             __NR_sendfile64
#define SYS_lchown32               __NR_lchown32
#define SYS_poll                   __NR_poll
#define SYS_inotify_init           __NR_inotify_init
#define SYS_getegid                __NR_getegid
#define SYS_pivot_root             __NR_pivot_root
#define SYS_personality            __NR_personality
#define SYS_open_by_handle_at      __NR_open_by_handle_at
#define SYS_getitimer              __NR_getitimer
#define SYS_epoll_pwait            __NR_epoll_pwait
#define SYS_getrlimit              __NR_getrlimit
#define SYS_getcwd                 __NR_getcwd
#define SYS_gettimeofday           __NR_gettimeofday
#define SYS_renameat               __NR_renameat
#define SYS_mpx                    __NR_mpx
#define SYS_oldolduname            __NR_oldolduname
#define SYS_execve                 __NR_execve
#define SYS_sigreturn              __NR_sigreturn
#define SYS_chroot                 __NR_chroot
#define SYS_idle                   __NR_idle
#define SYS_execveat               __NR_execveat
#define SYS_ftruncate              __NR_ftruncate
#define SYS_request_key            __NR_request_key
#define SYS_getresuid32            __NR_getresuid32
#define SYS_getrandom              __NR_getrandom
#define SYS_getpid                 __NR_getpid
#define SYS_fsync                  __NR_fsync
#define SYS_munmap                 __NR_munmap
#define SYS_mount                  __NR_mount
#define SYS_getgid                 __NR_getgid
#define SYS_access                 __NR_access
#define SYS_oldstat                __NR_oldstat
#define SYS_inotify_init1          __NR_inotify_init1
#define SYS_fallocate              __NR_fallocate
#define SYS_rt_sigtimedwait        __NR_rt_sigtimedwait
#define SYS_alarm                  __NR_alarm
#define SYS_nanosleep              __NR_nanosleep
#define SYS_sched_getattr          __NR_sched_getattr
#define SYS_getdents64             __NR_getdents64
#define SYS_inotify_add_watch      __NR_inotify_add_watch
#define SYS_socket                 __NR_socket
#define SYS_putpmsg                __NR_putpmsg
#define SYS_io_cancel              __NR_io_cancel
#define SYS_fanotify_mark          __NR_fanotify_mark
#define SYS_exit                   __NR_exit
#define SYS_set_thread_area        __NR_set_thread_area
#define SYS_lstat                  __NR_lstat
#define SYS_init_module            __NR_init_module
#define SYS_prof                   __NR_prof
#define SYS_timer_gettime          __NR_timer_gettime
#define SYS_creat                  __NR_creat

#endif /* LIBC_SYS_SYSCALL_H_ */
